name: Deploy Azure Functions (Backend)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install and validate dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r backend/requirements.txt

      - name: Create deployment package
        run: |
          cd backend
          zip -r ../release.zip .

      - uses: actions/upload-artifact@v4
        with:
          name: python-backend
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-backend

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B2D2AD9F11C2489498AE3FCC98165B35 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_002544C916EC47CD8E54397E2A7855F8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CA71D4BB8F684E3DAAFE18AF05F7CF8D }}

      - name: Check Azure access
        run: |
         az account show -o table

          echo "CHECK FUNCTION:"
          az functionapp show \
            --name sba-inventory-api-viktorbevz \
            --resource-group SBA-Project-RG \
            -o table

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: sba-inventory-api-viktorbevz
          resource-group-name: SBA-Project-RG
          package: .