name: Deploy Frontend to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Package frontend
        run: |
          cd frontend
          zip -r ../frontend.zip . --exclude "*.DS_Store"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          # Тебе нужно будет создать один секрет AZURE_CREDENTIALS 
          # с JSON-объектом внутри (Client ID, Tenant ID, Subscription ID)
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: frontend
          package: frontend.zip
